homepage: "http://nginx.org"
main_repo: "https://github.com/nginx/nginx"
language: c
primary_contact: "xim.XXX@gmail.com"
auto_ccs:
  - pluknet@gmail.com
  - david@adalogics.com
sanitizers:
  - address

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

